import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fffaf7',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  title: {
    fontSize: 36,
    fontWeight: '700',
    color: '#3d2a2a',
    marginBottom: 12,
  },
  subtitle: {
    fontSize: 18,
    color: '#5c4a4a',
    textAlign: 'center',
    marginBottom: 28,
    lineHeight: 26,
  },
  primaryButton: {
    backgroundColor: '#a95d5d',
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  listContainer: {
    flex: 1,
    backgroundColor: '#fff5f1',
    padding: 16,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#f0d7d0',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  cardTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#332727',
    marginBottom: 6,
  },
  cardBrand: {
    fontSize: 16,
    color: '#7d6565',
    marginBottom: 6,
  },
  cardPrice: {
    fontSize: 16,
    color: '#a95d5d',
    fontWeight: '700',
  },
  detailContainer: {
    flexGrow: 1,
    backgroundColor: '#fffaf7',
    padding: 22,
  },
  detailName: {
    fontSize: 30,
    fontWeight: '700',
    color: '#2d2121',
    marginBottom: 8,
  },
  detailBrand: {
    fontSize: 18,
    color: '#7d6565',
    marginBottom: 8,
  },
  detailPrice: {
    fontSize: 20,
    fontWeight: '700',
    color: '#a95d5d',
    marginBottom: 18,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginTop: 12,
    marginBottom: 6,
    color: '#3d2a2a',
  },
  detailText: {
    fontSize: 16,
    lineHeight: 24,
    color: '#4e3c3c',
  },
  secondaryButton: {
    marginTop: 24,
    backgroundColor: '#3d2a2a',
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 10,
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});